name: bank-connector

permissions: read-all

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:

jobs:

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # only use one version for the lint step
        python-version: [ "3.9" ]
        poetry-version: [ "1.1.13" ]
    steps:
      - id: checkout-code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - id: prepare-python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - id: prepare-poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - id: dependencies
        run: |
          poetry install

      - id: pyLint
        run: poetry run pylint bank_connector tests

  test:
    runs-on: ${{ matrix.os }}
    needs: lint
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        python-version: [ '3.9', '3.10' ]
        poetry-version: [ "1.1.13" ]

    steps:
      - id: checkout-code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - id: prepare-python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - id: prepare-poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - id: dependencies
        run: |
          poetry install

      - id: pytest
        run: |
          poetry run pytest
